### ISSUE TITLE
Error message when creating the administrator

### ISSUE THREAD

**Issue by fifty1-linh** [atrocore/atrodam#111]
I receive an error message during the setup process. When I submit the form for the administrator following error occurs:
![Screenshot at Jun 06 15-14-54](https://github.com/atrocore/atrodam/assets/60695550/b8953a85-18a8-418a-b84e-89c510cab47a)

Logfile:
`[2023-06-06T11:25:55.088651+00:00] Log.ERROR: Installer Error: Error while rebuilding database. See log file for details. | #0 /var/www/vhosts/mydam.com/dam.mydam.com/vendor/atrocore/core/app/Espo/Core/DataManager.php(193): Espo\Core\DataManager->rebuildDatabase() #1 /var/www/vhosts/mydam.com/dam.mydam.com/vendor/atrocore/core/app/Espo/Services/Installer.php(625): Espo\Core\DataManager->rebuild() #2 /var/www/vhosts/mydam.com/dam.mydam.com/vendor/atrocore/core/app/Espo/Services/Installer.php(240): Espo\Services\Installer->prepareDataBase() #3 /var/www/vhosts/mydam.com/dam.mydam.com/vendor/atrocore/core/app/Espo/Controllers/Installer.php(153): Espo\Services\Installer->createAdmin() #4 /var/www/vhosts/mydam.com/dam.mydam.com/vendor/atrocore/core/app/Espo/Core/ControllerManager.php(154): Espo\Controllers\Installer->actionCreateAdmin() #5 /var/www/vhosts/mydam.com/dam.mydam.com/vendor/atrocore/core/app/Espo/Core/Application.php(427): Espo\Core\ControllerManager->process() #6 /var/www/vhosts/mydam.com/dam.mydam.com/vendor/atrocore/core/app/Espo/Core/Application.php(230): Espo\Core\Application->runInstallerApi() #7 /var/www/vhosts/mydam.com/dam.mydam.com/vendor/atrocore/core/app/Espo/Core/Application.php(149): Espo\Core\Application->runApi() #8 /var/www/vhosts/mydam.com/dam.mydam.com/index.php(18): Espo\Core\Application->run() #9 {main} [] []
[2023-06-06T12:02:26.447238+00:00] Log.ALERT: Rebuild database fault: PDOException: SQLSTATE[HY000]: General error: 1283 Column 'sku' cannot be part of FULLTEXT index in /var/www/vhosts/mydam.com/dam.mydam.com/vendor/doctrine/dbal/src/Driver/PDO/Connection.php:72 Stack trace: #0 /var/www/vhosts/mydam.com/dam.mydam.com/vendor/doctrine/dbal/src/Driver/PDO/Connection.php(72): PDO->query() #1 /var/www/vhosts/mydam.com/dam.mydam.com/vendor/doctrine/dbal/src/Connection.php(1035): Doctrine\DBAL\Driver\PDO\Connection->query() #2 /var/www/vhosts/mydam.com/dam.mydam.com/vendor/atrocore/core/app/Treo/Core/Utils/Database/Schema/Schema.php(103): Doctrine\DBAL\Connection->executeQuery() #3 /var/www/vhosts/mydam.com/dam.mydam.com/vendor/atrocore/core/app/Espo/Core/DataManager.php(230): Treo\Core\Utils\Database\Schema\Schema->rebuild() #4 /var/www/vhosts/mydam.com/dam.mydam.com/vendor/atrocore/core/app/Espo/Core/DataManager.php(193): Espo\Core\DataManager->rebuildDatabase() #5 /var/www/vhosts/mydam.com/dam.mydam.com/vendor/atrocore/core/app/Espo/Services/Installer.php(625): Espo\Core\DataManager->rebuild() #6 /var/www/vhosts/mydam.com/dam.mydam.com/vendor/atrocore/core/app/Espo/Services/Installer.php(240): Espo\Services\Installer->prepareDataBase() #7 /var/www/vhosts/mydam.com/dam.mydam.com/vendor/atrocore/core/app/Espo/Controllers/Installer.php(153): Espo\Services\Installer->createAdmin() #8 /var/www/vhosts/mydam.com/dam.mydam.com/vendor/atrocore/core/app/Espo/Core/ControllerManager.php(154): Espo\Controllers\Installer->actionCreateAdmin() #9 /var/www/vhosts/mydam.com/dam.mydam.com/vendor/atrocore/core/app/Espo/Core/Application.php(427): Espo\Core\ControllerManager->process() #10 /var/www/vhosts/mydam.com/dam.mydam.com/vendor/atrocore/core/app/Espo/Core/Application.php(230): Espo\Core\Application->runInstallerApi() #11 /var/www/vhosts/mydam.com/dam.mydam.com/vendor/atrocore/core/app/Espo/Core/Application.php(149): Espo\Core\Application->runApi() #12 /var/www/vhosts/mydam.com/dam.mydam.com/index.php(18): Espo\Core\Application->run() #13 {main}  Next Doctrine\DBAL\Driver\PDO\Exception: SQLSTATE[HY000]: General error: 1283 Column 'sku' cannot be part of FULLTEXT index in /var/www/vhosts/mydam.com/dam.mydam.com/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:26 Stack trace: #0 /var/www/vhosts/mydam.com/dam.mydam.com/vendor/doctrine/dbal/src/Driver/PDO/Connection.php(77): Doctrine\DBAL\Driver\PDO\Exception::new() #1 /var/www/vhosts/mydam.com/dam.mydam.com/vendor/doctrine/dbal/src/Connection.php(1035): Doctrine\DBAL\Driver\PDO\Connection->query() #2 /var/www/vhosts/mydam.com/dam.mydam.com/vendor/atrocore/core/app/Treo/Core/Utils/Database/Schema/Schema.php(103): Doctrine\DBAL\Connection->executeQuery() #3 /var/www/vhosts/mydam.com/dam.mydam.com/vendor/atrocore/core/app/Espo/Core/DataManager.php(230): Treo\Core\Utils\Database\Schema\Schema->rebuild() #4 /var/www/vhosts/mydam.com/dam.mydam.com/vendor/atrocore/core/app/Espo/Core/DataManager.php(193): Espo\Core\DataManager->rebuildDatabase() #5 /var/www/vhosts/mydam.com/dam.mydam.com/vendor/atrocore/core/app/Espo/Services/Installer.php(625): Espo\Core\DataManager->rebuild() #6 /var/www/vhosts/mydam.com/dam.mydam.com/vendor/atrocore/core/app/Espo/Services/Installer.php(240): Espo\Services\Installer->prepareDataBase() #7 /var/www/vhosts/mydam.com/dam.mydam.com/vendor/atrocore/core/app/Espo/Controllers/Installer.php(153): Espo\Services\Installer->createAdmin() #8 /var/www/vhosts/mydam.com/dam.mydam.com/vendor/atrocore/core/app/Espo/Core/ControllerManager.php(154): Espo\Controllers\Installer->actionCreateAdmin() #9 /var/www/vhosts/mydam.com/dam.mydam.com/vendor/atrocore/core/app/Espo/Core/Application.php(427): Espo\Core\ControllerManager->process() #10 /var/www/vhosts/mydam.com/dam.mydam.com/vendor/atrocore/core/app/Espo/Core/Application.php(230): Espo\Core\Application->runInstallerApi() #11 /var/www/vhosts/mydam.com/dam.mydam.com/vendor/atrocore/core/app/Espo/Core/Application.php(149): Espo\Core\Application->runApi() #12 /var/www/vhosts/mydam.com/dam.mydam.com/index.php(18): Espo\Core\Application->run() #13 {main}  Next Doctrine\DBAL\Exception\DriverException: An exception occurred while executing a query: SQLSTATE[HY000]: General error: 1283 Column 'sku' cannot be part of FULLTEXT index in /var/www/vhosts/mydam.com/dam.mydam.com/vendor/doctrine/dbal/src/Driver/API/MySQL/ExceptionConverter.php:119 Stack trace: #0 /var/www/vhosts/mydam.com/dam.mydam.com/vendor/doctrine/dbal/src/Connection.php(1768): Doctrine\DBAL\Driver\API\MySQL\ExceptionConverter->convert() #1 /var/www/vhosts/mydam.com/dam.mydam.com/vendor/doctrine/dbal/src/Connection.php(1707): Doctrine\DBAL\Connection->handleDriverException() #2 /var/www/vhosts/mydam.com/dam.mydam.com/vendor/doctrine/dbal/src/Connection.php(1040): Doctrine\DBAL\Connection->convertExceptionDuringQuery() #3 /var/www/vhosts/mydam.com/dam.mydam.com/vendor/atrocore/core/app/Treo/Core/Utils/Database/Schema/Schema.php(103): Doctrine\D... [] []
[2023-06-06T12:02:27.539241+00:00] Log.ERROR: Installer Error: Error while rebuilding database. See log file for details. | #0 /var/www/vhosts/mydam.com/dam.mydam.com/vendor/atrocore/core/app/Espo/Core/DataManager.php(193): Espo\Core\DataManager->rebuildDatabase() #1 /var/www/vhosts/mydam.com/dam.mydam.com/vendor/atrocore/core/app/Espo/Services/Installer.php(625): Espo\Core\DataManager->rebuild() #2 /var/www/vhosts/mydam.com/dam.mydam.com/vendor/atrocore/core/app/Espo/Services/Installer.php(240): Espo\Services\Installer->prepareDataBase() #3 /var/www/vhosts/mydam.com/dam.mydam.com/vendor/atrocore/core/app/Espo/Controllers/Installer.php(153): Espo\Services\Installer->createAdmin() #4 /var/www/vhosts/mydam.com/dam.mydam.com/vendor/atrocore/core/app/Espo/Core/ControllerManager.php(154): Espo\Controllers\Installer->actionCreateAdmin() #5 /var/www/vhosts/mydam.com/dam.mydam.com/vendor/atrocore/core/app/Espo/Core/Application.php(427): Espo\Core\ControllerManager->process() #6 /var/www/vhosts/mydam.com/dam.mydam.com/vendor/atrocore/core/app/Espo/Core/Application.php(230): Espo\Core\Application->runInstallerApi() #7 /var/www/vhosts/mydam.com/dam.mydam.com/vendor/atrocore/core/app/Espo/Core/Application.php(149): Espo\Core\Application->runApi() #8 /var/www/vhosts/mydam.com/dam.mydam.com/index.php(18): Espo\Core\Application->run() #9 {main} [] []`

Any idea how to solve this issue?

**Comment by rratsun** [comment]
Hello,

Send us your system configuration. PHP version, mysql version etc.
